[platformio]
default_envs = main_unit

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:main_unit]
build_src_filter =
    +<*.cpp>
    +<main_unit/>
    -<remote_unit/>

[env:remote_unit]
build_src_filter =
    +<*.cpp>
    +<remote_unit/>
    -<main_unit/>

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SH110X